name: AML Mod Compiler

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4

      - name: Get AML Template
        run: |
          wget -O AML_src.zip https://github.com/RusJJ/AndroidModLoader/archive/refs/heads/main.zip
          unzip AML_src.zip
          mv AndroidModLoader-main/mod ./mod

      - name: Get SAUtils (Public)
        run: |
          git clone https://github.com/RusJJ/SAUtils.git ./mod/SAUtils

      - name: Get Structs (Public)
        run: |
          git clone https://github.com/RusJJ/GTASAAndroid_Structs.git ./structs

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build Mod
        run: |
          ndk-build -j$(nproc)

      - name: Upload Finished Mod
        uses: actions/upload-artifact@v4
        with:
          name: SkyGfx-Android-32bit
          path: libs/
          
